name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6

      - name: Upload build for test runner
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./

  test:
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./

      - uses: php-actions/phpunit@v3
